name: test-you-porn
on: [push, workflow_dispatch]
jobs:
  tests:
    name: test-you-porn
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.6.1', '3.6', '3.7.1', '3.7', '3.8.1', '3.8', '3.9.1', '3.9', '3.10.1', '3.10', '3.11-dev', 'pypy-3.6-v7.3.3', 'pypy-3.7-v7.3.3', 'pypy-3.8-v7.3.6', 'pypy-3.9-v7.3.8', 'pypy-3.7', 'pypy-3.8', 'pypy-3.9']
    steps:
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install yt-dlp
      run: pip install yt-dlp
    - name: Run tests
      run: yt-dlp -vU "https://www.youporn.com/watch/16516654/sego-lamico-di-mio-marito-al-ristorante-e-non-si-accorge-di-niente/" --list-formats
